export const FETCH_DASHBOARD_STATS_REQUEST = "FETCH_DASHBOARD_STATS_REQUEST";
export const FETCH_DASHBOARD_STATS_SUCCESS = "FETCH_DASHBOARD_STATS_SUCCESS";
export const FETCH_DASHBOARD_STATS_FAILURE = "FETCH_DASHBOARD_STATS_FAILURE";

export const FETCH_REVENUE_CHART_REQUEST = "FETCH_REVENUE_CHART_REQUEST";
export const FETCH_REVENUE_CHART_SUCCESS = "FETCH_REVENUE_CHART_SUCCESS";
export const FETCH_REVENUE_CHART_FAILURE = "FETCH_REVENUE_CHART_FAILURE";

export const FETCH_ORDERS_CHART_REQUEST = "FETCH_ORDERS_CHART_REQUEST";
export const FETCH_ORDERS_CHART_SUCCESS = "FETCH_ORDERS_CHART_SUCCESS";
export const FETCH_ORDERS_CHART_FAILURE = "FETCH_ORDERS_CHART_FAILURE";

export const FETCH_TOP_PRODUCTS_REQUEST = "FETCH_TOP_PRODUCTS_REQUEST";
export const FETCH_TOP_PRODUCTS_SUCCESS = "FETCH_TOP_PRODUCTS_SUCCESS";
export const FETCH_TOP_PRODUCTS_FAILURE = "FETCH_TOP_PRODUCTS_FAILURE";

export const FETCH_RECENT_ORDERS_REQUEST = "FETCH_RECENT_ORDERS_REQUEST";
export const FETCH_RECENT_ORDERS_SUCCESS = "FETCH_RECENT_ORDERS_SUCCESS";
export const FETCH_RECENT_ORDERS_FAILURE = "FETCH_RECENT_ORDERS_FAILURE";

export const CLEAR_DASHBOARD_ERROR = "CLEAR_DASHBOARD_ERROR";

